/* Auto-generated from Excel. Do not edit manually. */
#include "DeviceRegisters.h"
#include <assert.h>

const reg_meta_t g_reg_meta[REG__COUNT] = {
    {
        .id = REG_CONTROL,
        .index = 0u,
        .size = 2u,
        .type = REG_T_U16,
        .access = REG_ACC_W,
        .name = "CONTROL",
        .units = "bitfield",
    },
    {
        .id = REG_STATUS,
        .index = 1u,
        .size = 2u,
        .type = REG_T_U16,
        .access = REG_ACC_R,
        .name = "STATUS",
        .units = "bitfield",
    },
    {
        .id = REG_ERROR_CODE,
        .index = 2u,
        .size = 2u,
        .type = REG_T_U16,
        .access = REG_ACC_R,
        .name = "ERROR_CODE",
        .units = "",
    },
    {
        .id = REG_MODE,
        .index = 3u,
        .size = 2u,
        .type = REG_T_U16,
        .access = REG_ACC_RW,
        .name = "MODE",
        .units = "",
    },
    {
        .id = REG_CMD,
        .index = 4u,
        .size = 2u,
        .type = REG_T_U16,
        .access = REG_ACC_W,
        .name = "CMD",
        .units = "",
    },
    {
        .id = REG_CURRENT_POS_16,
        .index = 16u,
        .size = 2u,
        .type = REG_T_I16,
        .access = REG_ACC_R,
        .name = "CURRENT_POS_16",
        .units = "step",
    },
    {
        .id = REG_CURRENT_VELOCITY_16,
        .index = 17u,
        .size = 2u,
        .type = REG_T_I16,
        .access = REG_ACC_R,
        .name = "CURRENT_VELOCITY_16",
        .units = "8 step/s",
    },
    {
        .id = REG_CURRENT_ACCEL_16,
        .index = 18u,
        .size = 2u,
        .type = REG_T_I16,
        .access = REG_ACC_R,
        .name = "CURRENT_ACCEL_16",
        .units = "256 step/s²",
    },
    {
        .id = REG_TARGET_POS_16,
        .index = 19u,
        .size = 2u,
        .type = REG_T_I16,
        .access = REG_ACC_RW,
        .name = "TARGET_POS_16",
        .units = "step",
    },
    {
        .id = REG_MAX_VELOCITY_16,
        .index = 20u,
        .size = 2u,
        .type = REG_T_U16,
        .access = REG_ACC_RW,
        .name = "MAX_VELOCITY_16",
        .units = "8 step/s",
    },
    {
        .id = REG_MAX_ACCEL_16,
        .index = 21u,
        .size = 2u,
        .type = REG_T_U16,
        .access = REG_ACC_RW,
        .name = "MAX_ACCEL_16",
        .units = "256 step/s²",
    },
    {
        .id = REG_MOVE_POS_REL_16,
        .index = 22u,
        .size = 2u,
        .type = REG_T_I16,
        .access = REG_ACC_W,
        .name = "MOVE_POS_REL_16",
        .units = "step",
    },
    {
        .id = REG_CURRENT_POS_32,
        .index = 32u,
        .size = 4u,
        .type = REG_T_I32,
        .access = REG_ACC_R,
        .name = "CURRENT_POS_32",
        .units = "step",
    },
    {
        .id = REG_CURRENT_VELOCITY_32,
        .index = 34u,
        .size = 4u,
        .type = REG_T_I32,
        .access = REG_ACC_R,
        .name = "CURRENT_VELOCITY_32",
        .units = "step/sec",
    },
    {
        .id = REG_CURRENT_ACCEL_32,
        .index = 36u,
        .size = 4u,
        .type = REG_T_I32,
        .access = REG_ACC_R,
        .name = "CURRENT_ACCEL_32",
        .units = "step/sec²",
    },
    {
        .id = REG_TARGET_POS_32,
        .index = 38u,
        .size = 4u,
        .type = REG_T_I32,
        .access = REG_ACC_RW,
        .name = "TARGET_POS_32",
        .units = "step",
    },
    {
        .id = REG_MAX_VELOCITY_32,
        .index = 40u,
        .size = 4u,
        .type = REG_T_U32,
        .access = REG_ACC_RW,
        .name = "MAX_VELOCITY_32",
        .units = "step/sec",
    },
    {
        .id = REG_MAX_ACCEL_32,
        .index = 42u,
        .size = 4u,
        .type = REG_T_U32,
        .access = REG_ACC_RW,
        .name = "MAX_ACCEL_32",
        .units = "step/sec²",
    },
    {
        .id = REG_MOVE_POS_REL_32,
        .index = 44u,
        .size = 4u,
        .type = REG_T_I32,
        .access = REG_ACC_W,
        .name = "MOVE_POS_REL_32",
        .units = "step",
    },
};

const reg_meta_t* reg_get_meta(reg_id_t id)
{
    assert((int)id >= 0 && id < REG__COUNT);
    return &g_reg_meta[id];
}

