#include "FreeRTOS.h"

// 1. Критичные прерывания (самый высокий)
#define PRIORITY_CRITICAL_ISR    	(configMAX_PRIORITIES - 1)
#define PRIORITY_HIGH   					(configMAX_PRIORITIES - 3)
#define PRIORITY_ABOVE_NORMAL     (configMAX_PRIORITIES - 4)
#define PRIORITY_NORMAL          	(configMAX_PRIORITIES - 5)
#define PRIORITY_BELOW_NORMAL     (configMAX_PRIORITIES - 6)
#define PRIORITY_LOW     					(configMAX_PRIORITIES - 7)
#define PRIORITY_IDLE            	(tskIDLE_PRIORITY)


#define MODBUS_TASK_PRIORITY  PRIORITY_NORMAL
#define MOTOR_CONTROLLER_TIMER_ISR_PRIORITY PRIORITY_CRITICAL_ISR



#define MAX_STEPPER_MOTOR_COUNT 5u

#define USE_DMA_FOR_USART1_MODBUS 1
#define MODBUS_SLAVE_ADRESS 1

#define MOTION_PROFILE_RECALC_IN_TASK 1

#define USE_HW_CRC_UNIT 1










// Stepper motor controller debug hooks (override if needed)
#ifndef STEPPER_MOTOR_CONTROLLER_IRQ_START_HOOK
#define STEPPER_MOTOR_CONTROLLER_IRQ_START_HOOK() \
	//LL_GPIO_SetOutputPin(PC11_GPIO_Port, PC11_Pin)
#endif

#ifndef STEPPER_MOTOR_CONTROLLER_TIMERS_UPDATED_HOOK
#define STEPPER_MOTOR_CONTROLLER_TIMERS_UPDATED_HOOK() \
	//LL_GPIO_ResetOutputPin(PC11_GPIO_Port, PC11_Pin)
#endif